package com.majiang.community.mapper;

import com.majiang.community.model.Inform;
import com.majiang.community.model.InformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    long countByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int deleteByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int insertSelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    List<Inform> selectByExampleWithRowbounds(InformExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    List<Inform> selectByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    Inform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int updateByExample(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int updateByPrimaryKeySelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    int updateByPrimaryKey(Inform record);
}