package com.majiang.community.model;

public class Inform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.status
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.type
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.gmt_create
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.inform_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Long informUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.inform_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Long informId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.inform_title
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private String informTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.begin_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private Long beginUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.begin_user_name
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    private String beginUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.id
     *
     * @return the value of inform.id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.id
     *
     * @param id the value for inform.id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.status
     *
     * @return the value of inform.status
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.status
     *
     * @param status the value for inform.status
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.type
     *
     * @return the value of inform.type
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.type
     *
     * @param type the value for inform.type
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.gmt_create
     *
     * @return the value of inform.gmt_create
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.gmt_create
     *
     * @param gmtCreate the value for inform.gmt_create
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.inform_user_id
     *
     * @return the value of inform.inform_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Long getInformUserId() {
        return informUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.inform_user_id
     *
     * @param informUserId the value for inform.inform_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setInformUserId(Long informUserId) {
        this.informUserId = informUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.inform_id
     *
     * @return the value of inform.inform_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Long getInformId() {
        return informId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.inform_id
     *
     * @param informId the value for inform.inform_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setInformId(Long informId) {
        this.informId = informId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.inform_title
     *
     * @return the value of inform.inform_title
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public String getInformTitle() {
        return informTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.inform_title
     *
     * @param informTitle the value for inform.inform_title
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setInformTitle(String informTitle) {
        this.informTitle = informTitle == null ? null : informTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.begin_user_id
     *
     * @return the value of inform.begin_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public Long getBeginUserId() {
        return beginUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.begin_user_id
     *
     * @param beginUserId the value for inform.begin_user_id
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setBeginUserId(Long beginUserId) {
        this.beginUserId = beginUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.begin_user_name
     *
     * @return the value of inform.begin_user_name
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public String getBeginUserName() {
        return beginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.begin_user_name
     *
     * @param beginUserName the value for inform.begin_user_name
     *
     * @mbg.generated Mon Sep 16 13:08:20 CST 2019
     */
    public void setBeginUserName(String beginUserName) {
        this.beginUserName = beginUserName == null ? null : beginUserName.trim();
    }
}